### ISSUE TITLE
Missing images

### ISSUE THREAD

**Issue by sultanoswing** [fernadosilva/orvfms#11]
Thanks for the useful software. Got it _mostly_ working i.e. the server is running (at 'localhost/s20') and successfully controls my s20.

However, there are no images and the css seems messed up as per the screenshot below. I have edited all the paths in 'orvfms.css' and 'index.php' as instructed. Perhaps I'm missing a path somewhere?

I should add - hpptd is running under Arch Linux, using php7. DocumentSource directory is "/srv/http", with orvfsm files in "/srv/http/orvfsm-master/". Same issue under Chrome and Firefox.

![screenshot from 2016-09-11 12-48-11](https://cloud.githubusercontent.com/assets/22124274/18414493/c2a2f67a-781e-11e6-83d5-f0b0ad6adbc5.png)

**Comment by sultanoswing** [comment]
Solved. It was a paths problem. I probably should have read the directions more closely :)

I now have all of the orvfms-master files unzipped into my "/srv/http/" directory i.e.
"/srv/http/s20/index.php" ; "srv/http/lib/orvfms/_.php" ; "/srv/http/img/_.png" and "/srv/http/css/orvfms.css"

I edited the paths in orvfms.css to simply e.g. "background-image:url(clock_simple.png);" and it's all working now :)

**Comment by fernadosilva** [comment]
Hello,

Sorry for my silence, but only now I saw your message. I am glad that everything is working now!

Regards,

— fernando

**Comment by sultanoswing** [comment]
No problem! I am just very grateful for the excellent piece of
software....why the company itself won't do a browser page is beyond me.
Roll on the open source community!

Thanks,
Curtis
