### ISSUE TITLE
php 7.1.1 support

### ISSUE THREAD

**Issue by exetico** [fernadosilva/orvfms#14]
Hi'

Is it working with the php 7.1.1 lib? :-)

Best regards,

**Comment by sultanoswing** [comment]
Yes, no problems for me under Arch Linux (php 7.7.1).

**Comment by sultanoswing** [comment]
Sorry - that should have read php 7.1.1!

**Comment by exetico** [comment]
@sultanoswing - Damn. I actually just messed something up with my docker. All good from here, just tested it in a docker :-) Thanks for taking you time to answer the issue.

**Comment by fernadosilva** [comment]
Hello all,

**Comment by fernadosilva** [comment]
Sorry for not commenting before, but my time for orvfms support is now quite tight. Anyway, great that you sorted it out. Rgds.
