### ISSUE TITLE
Synchronising Socket Clocks Automatically

### ISSUE THREAD

**Issue by javaftper** [fernadosilva/orvfms#17]
Can the project be updated to automatically synch socket with the local server?

This project was recently updated to fix the NTP issue caused by Orvibo terminating their server.  Thanks very much for the fix provided.

**Background**
Following the termination of the NTP/datetime synchronisation server by orvibo earlier this year the s20 switches can no longer automatically synchronise their internal clock.  

As a result if power is lost/unplugged it defaults to 1900-01-01T00:00:00 and begins incrementing when power is restored.

Also I believe the socket must use the electrical frequency of the local electricity supplier in order to regulate its counter in a similar way to most boilers, ovens etc meaning that it regularly loses/gains seconds depending on whether the frequency is above or below 50mHz or similar.  This results in the sockets going out of sync with the server time.

**Impact**
Not having the correct time impacts any schedules the user has set for automation of the sockets.

**Suggestion**
I believe the socket time should be automatically synchronised to the local server time whenever the index page is loaded and once every 24 hours the page is open (in case people don't load the index page regularly and just leave the page open on server- I believe I have seen this already in the code for a different purpose).

Previously this suggestion may have caused people issues if they preferred to use the NTP time but now I can see no benefit and several disadvantages to not automatically synchronising the clocks.

**Implementation Suggestion**
Add a global Boolean variable to globals.php called AUTO_SYNCH_DATETIME which I would suggest is defaulted to true.

Add an if statement checking the synchronisation status of the socket to the appropriate point in index.php (around line 275) then utilise the setSocketTime function within orvfms.php to synchronise the socket if it is not currently synchronised with the local server.

Add a function to run every 24 hours to synchronise any unsynchronised clocks when the page is left open on the server- document that this is recommended for people who don't use the index page regularly.

**Comment by sultanoswing** [comment]
Good pick up! I wondered why my s20's time had gone haywire after switching
the socket off a couple of weeks ago.

Would be great if this could be implemented.

**Comment by javaftper** [comment]
V1.2 fixed this issue thanks.

**Comment by sultanoswing** [comment]
Brilliant - thanks! Missed the autosync update somehow, but now up and running. Great work to you and Fernando.
