### ISSUE TITLE
Relative paths don't work ootb

### ISSUE THREAD

**Issue by ghost** [fernadosilva/orvfms#2]
Relative paths did not work for me when I tried to run the php development server with `php -S 0.0.0.0:9999 -t .`

I managed to get it working without hardcoding local paths using `$_SERVER["DOCUMENT_ROOT"]`:

``` diff
diff --git a/s20/index.php b/s20/index.php
index 33b4767..ff20b95 100644
--- a/s20/index.php
+++ b/s20/index.php
@@ -74,8 +74,8 @@ S20 remote
 /* UPDATE THE PATH to THE  orvfms LIBRARY and img directory 
    BELOW TO MATCH YOUR LOCAL CONFIGURATION.              
 */
-define("ORVFMS_PATH","../lib/orvfms/");
-define("IMG_PATH","../img/");
+define("ORVFMS_PATH",$_SERVER["DOCUMENT_ROOT"]."/lib/");
+define("IMG_PATH",$_SERVER["DOCUMENT_ROOT"]."/img/");

 require_once(ORVFMS_PATH."orvfms.php"); 

@@ -193,4 +193,4 @@ else{

 ?>
 </body>


-</html>
\ No newline at end of file
+</html>
```

**Comment by fernadosilva** [comment]
Thank you for your comment and proposed solution. I would say that the relative paths should work. Can you please just tell me in which environment and SO did you test it? Where did you store the index.php file? In the root directory? Or in $_SERVER["DOCUMENT_ROOT"]/s20?

Thanks once more for your help.

**Comment by ghost** [comment]
@fernadosilva: The environments I tested on were ubuntu with PHP 5.6.4 and OSX with the built in PHP (5.5.27). On both I was getting errors in the includes. As a web server I used the built-in development server `php -S 0.0.0.0:9999 -t .`

I left the index.php in it's own folder, i.e. `$_SERVER["DOCUMENT_ROOT"]/s20`, and the dev server was started in DOCUMENT_ROOT.

**Comment by fernadosilva** [comment]
Sure, you were 100% right. Git directories differed from my development environment (and since I have a few scripts to update it, I did not remember it). Dirs, corrected, must work OOTB now. 

Thanks for the warning.
