### ISSUE TITLE
Colours change

### ISSUE THREAD

**Issue by bezik46** [fernadosilva/orvfms#5]
I can not get the index page colours to display correctly.
Socket is ON, index.php shows green, actions, socket has green circle next to it.
So far so good.
Chose action OFF / Now. Sockets gets switched OFF & we are returned to index page which is STILL green!

Go on Timer page, socket shows red circle (correct), Done & we are returned to RED (correct) index

So it is the initial flick from action to index that does not quickly change the colour

sebus

**Comment by fernadosilva** [comment]
Hello,

Hmmm… When a countdown occurs, I took the care of refreshing  the page only about 500ms later in order to give time to the switch change and the php software to read the new (updated) state. Can you please let me know which OS and browser are you using?

Rgds, 

Fernando M Silva

**Comment by bezik46** [comment]
Palemoon x64 on Win 10 x64, IE 11 on Server 2012 R2, IE 11 on Win 10 x64. Same on each one
Maybe the refresh wait is not long enough?

**Comment by scerazy** [comment]
Palemoon x64 on Win 10 x64, IE 11 on Server 2012 R2, IE 11 on Win 10 x64. Same on each one
Maybe the refresh wait is not long enough?

**Comment by fernadosilva** [comment]
Hello,

Sorry for the delay, but I suspended the work on this in the last few weeks for lack of time. I was reviewing my code now and I did not find any issue. 

But I was reviewing your text and it seems to me that you may be getting it wrong. To switch on/off NOW, you just press the (big) buttons in the main page, in any place other than the small icons. What you call the "actions page" it seems to me that you are talking about the "count down timers page". These may work in one of two ways: you set a countdown value, choose now, and the count down starts immediately, or you set "after switch on" and the countdown starts when the switch is turned on (the action will be always off in this case). But if you choose "now" with a countdown of 0:0:0, the colour may in fact fail at once and will only be updated in the next screen -- but this page was not intended to be used with 0:0:0. Try at least 1 second and it should work. For immediate actions, just use the main page.

Hope this helps.

fernando
