### ISSUE TITLE
After Delete - Search does not work anymore 

### ISSUE THREAD

**Issue by gkuhg** [fernadosilva/orvfms#7]
Hi,
Very useful code thanks for that. Unfortunately after a latest update with time zone, etc. the search does not work anymore (does not recognize the socket) after deletion. Could you please check and advise?
Thanks and regards,
George

**Comment by fernadosilva** [comment]
Hello,

Thank you for your interest. Unhappily, I am not able to reproduce your issue and in principle no changes were performed on that section of the code. 

a) Can you check if you have any relevant message on the log file of your web server?
b) Are you sure that you did not lock the device using the WiWo application (check switch -> more -> advanced) between your last search and the delete operation? If you did so, the code will not be able to find the device after deletion.
c)  When did you download the code? Can you download it again just to be sure that you have the very last version?

Best regards,

-- fernando

**Comment by gkuhg** [comment]
Thanks for your swift reply. After update to the latest update (just downloaded) the IP address is not shown anymore (Snapshot 1) and once pushing the "Delete device" then device cannot be find anymore (Snapshot 2). To get the device back I need to revert back to zip from 8.12.2015 and then find the device again (snapshot 3). I tried on raspberry pi3 and on my mac with Ampps and the effect is the same :(. Thanks in advance for your advices (may be I am missing some point).

**Snapshot 1:**
![bildschirmfoto 2016-04-18 um 20 58 19](https://cloud.githubusercontent.com/assets/18518664/14615932/5d356ae0-05a8-11e6-9004-9ba44b142980.png)
**Snapshot 2:**
![bildschirmfoto 2016-04-18 um 21 02 37](https://cloud.githubusercontent.com/assets/18518664/14616038/ecb51b16-05a8-11e6-8115-f191c8686f6c.png)
**Snapshot 3:**
![bildschirmfoto 2016-04-18 um 21 05 49](https://cloud.githubusercontent.com/assets/18518664/14616166/72f4f304-05a9-11e6-9eeb-97e52c675cd9.png)

**Comment by gkuhg** [comment]
I found the problem :).
It was in the mask:
define("IP_BROADCAST","192.168.**1**.255");
in my case it is:
define("IP_BROADCAST","192.168.**2**.255");

Thanks and regards,
George
